eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}
spring:
  application:
    name: customers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: root
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        boot:
          allow_jdbc_metadata_access: 'false'

server:
  port: '0'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
  endpoint:
    health:
      enabled: 'true'
      show-details: always

springdoc:
  api-docs:
    path: /docs-api
  packagesToScan: com.esand.clients.web.controller
  swagger-ui:
    path: /docs-ui.html