version: '3'

x-env: &db-config
  DB_HOST: postgres
  DB_PORT: 5432

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:19092

  postgres:
    image: postgres:16
    networks:
      - broker-kafka
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - broker-kafka
    ports:
      - "8082:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks:
      - broker-kafka
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    command: ["start-dev", "--import-realm", "--http-port=8081"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    ports:
      - "8761:8761"

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - server
      - postgres
    restart: unless-stopped
    environment:
      DEFAULT_ZONE: http://server:8761/eureka
      SPRING_PROFILES_ACTIVE: docker
      <<: *db-config
      KEYCLOAK_DEFAULT_URL: http://keycloak:8081

  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - server
      - postgres
    restart: unless-stopped
    environment:
      DEFAULT_ZONE: http://server:8761/eureka
      <<: *db-config
      SPRING_PROFILES_ACTIVE: docker

  delivery:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - server
      - products
      - postgres
    restart: unless-stopped
    environment:
      KAFKA_HOST: kafka:19092
      DEFAULT_ZONE: http://server:8761/eureka
      PRODUCTS_API_URL: http://gateway:8080/api/v1/products
      KEYCLOAK_DEFAULT_URL: http://keycloak:8081
      <<: *db-config
      SPRING_PROFILES_ACTIVE: docker

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - server
      - products
      - customers
      - delivery
      - postgres
    restart: unless-stopped
    environment:
      KAFKA_HOST: kafka:19092
      DEFAULT_ZONE: http://server:8761/eureka
      CUSTOMERS_API_URL: http://gateway:8080/api/v1/customers
      PRODUCTS_API_URL: http://gateway:8080/api/v1/products
      KEYCLOAK_DEFAULT_URL: http://keycloak:8081
      <<: *db-config
      SPRING_PROFILES_ACTIVE: docker

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - server
      - products
      - customers
      - delivery
      - orders
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DEFAULT_ZONE: http://server:8761/eureka
      KEYCLOAK_DEFAULT_URL: http://keycloak:8081

networks:
  broker-kafka:
    driver: bridge

volumes:
  pgdata:
