eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}


clients:
  api:
    url: ${CLIENTS_API_URL:http://localhost:8080/api/v1/clients}

products:
  api:
    url: ${PRODUCTS_API_URL:http://localhost:8080/api/v1/products}


spring:
  application:
    name: orders
  datasource:
    driverClassName: org.h2.Driver
    password: '1234'
    username: root
    url: jdbc:h2:file:./orders
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  h2:
    console:
      path: /h2-orders
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost:19092}

server:
  port: '0'
topic_name: Orders

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
  endpoint:
    health:
      enabled: 'true'
      show-details: always

springdoc:
  api-docs:
    path: /docs-api
  packagesToScan: com.esand.orders.web.controller
  swagger-ui:
    path: /docs-ui.html

keycloak:
  username: auth
  client-id: gateway
  client-realm: commerce
  client-secret: ouQ5I1dghJBhO9UlS3WGC1Mz7GRpMK5Tj
  password: 123
  token:
    url: http://localhost:8081/realms/commerce/protocol/openid-connect/token

feign:
  httpclient:
    enabled: 'true'