eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    ##### EXCLUIR DEPOIS ESSE NOME FIXO DE LOCALHOST PARA O DOCKER
    hostname: localhost
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}
spring:
  application:
    name: products
  datasource:
    driverClassName: org.h2.Driver
    password: '1234'
    username: root
    url: jdbc:h2:file:./products
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  h2:
    console:
      path: /h2-products
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'

server:
  port: '0'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
  endpoint:
    health:
      enabled: 'true'
      show-details: always