spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_DEFAULT_URL:http://localhost:8081}/realms/commerce/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: gateway
            authorization-grant-type: password
            scope: openid
            redirect-uri: http://localhost:8081
            client-authentication-method: post
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_DEFAULT_URL:http://localhost:8081}/realms/commerce/protocol/openid-connect/auth
            user-info-uri: ${KEYCLOAK_DEFAULT_URL:http://localhost:8081}/realms/commerce/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_DEFAULT_URL:http://localhost:8081}/realms/commerce/protocol/openid-connect/certs
            token-uri: ${KEYCLOAK_DEFAULT_URL:http://localhost:8081}/realms/commerce/protocol/openid-connect/token

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 8080