spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DEFAULT_KEYCLOAK:http://localhost:8081/realms/commerce}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 8080